### ISSUE TITLE
geminicommit not found in zsh

### ISSUE THREAD

**Issue by dakleckna** [tfkhdyt/geminicommit#3]
installed as specified via go install github.com/tfkhdyt/geminicommit@latest
beforehand updated GO 

but terminal doesnt seems to find "geminicommit"

OS Macbook Pro 16-inch, 2019 Intel

![geminicommit](https://github.com/tfkhdyt/geminicommit/assets/16823815/cb7e8dc8-f64d-431e-975c-4b7a0900349a)

**Comment by tfkhdyt** [comment]
Is there any error after you run the `go install` command?

**Comment by dakleckna** [comment]
unfortunately not

**Comment by tfkhdyt** [comment]
Give me the output of these commands:

```bash
echo $PATH

echo $GOPATH

echo $GOBIN
```

**Comment by dakleckna** [comment]
you had the right sense...
GOPATH and GOBIN are empty 👍
what should it? or how can i fill it up correctly?

**Comment by tfkhdyt** [comment]
Try this:

https://www.reddit.com/r/golang/comments/vycgel/comment/ig2e9wj

**Comment by tfkhdyt** [comment]
> Have you tried installing from binary instead of from source?
> 
> https://github.com/tfkhdyt/geminicommit/releases/tag/v0.0.4

you just have to extract the file, and then move the binary file to `/usr/local/bin`

**Comment by andersonbosa** [comment]
If you are going to download the binary you can also extract it directly to: `~/.local/bin/geminicommit`
![image](https://github.com/tfkhdyt/geminicommit/assets/8931900/1bc092ce-ef36-45bf-bc9e-b0cfc998d1c6)
