### ISSUE TITLE
Malware Detection by Kaspersky Security Network: VHO:Net-Worm.Win32.Kolab.gen

### ISSUE THREAD

**Issue by LSXAxeller** [tfkhdyt/geminicommit#7]
I scanned [geminicommit-v0.0.5-windows-amd64.zip](https://github.com/tfkhdyt/geminicommit/releases/download/v0.0.5/geminicommit-v0.0.5-windows-amd64.zip) on finishing download with Kaspersky and got Detected: VHO:Net-Worm.Win32.Kolab.gen on geminicommit.exe

![image](https://github.com/tfkhdyt/geminicommit/assets/56027532/761b6015-d9fd-4624-a2bc-24c4d8e9a2dc)
![image](https://github.com/tfkhdyt/geminicommit/assets/56027532/9b525935-1fb9-4c46-a386-675f745bb9d9)

**Comment by LSXAxeller** [comment]
Building from source is totally safe

**Comment by tfkhdyt** [comment]
I think it's related with upx. The official binary is compressed by upx

https://github.com/upx/upx/issues/337
